name: Deploy preview environment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image to Google Container Registry
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-app:$GITHUB_SHA
