name: Deploy preview environment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code of app
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud --version  # Verify installation

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode | jq > ./gcp_credential.json 
          gcloud auth activate-service-account --key-file=./gcp_credential.json 
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud auth list  # Verify authentication

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-east4-docker.pkg.dev
          docker build -t us-east4-docker.pkg.dev/poc-preview-api/poc-preview-app:$GITHUB_SHA .
          docker push  us-east4-docker.pkg.dev/poc-preview-api/poc-preview-app:$GITHUB_SHA
